#!/usr/bin/env python3
"""Build the curriculum-first Logical Thinking Adventures LKG blueprint."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "curriculum/logical-thinking-adventures/lkg/curriculum-first-p008-p043-v1.json"


def page(
    title: str,
    objective: str,
    instruction: str,
    thinking: str,
    model: dict[str, Any],
    response: str,
    archetype: str,
    mechanic: str,
    render_kind: str,
    assets: dict[str, str],
    controls: dict[str, Any],
    teacher_cue: str,
    *gates: str,
) -> dict[str, Any]:
    return {
        "title": title,
        "objective": objective,
        "instruction": instruction,
        "child_thinking": thinking,
        "model_example": model,
        "expected_response": response,
        "archetype": archetype,
        "mechanic": mechanic,
        "render_kind": render_kind,
        "illustration_assets": assets,
        "renderer_controls": controls,
        "teacher_cue": teacher_cue,
        "validation_gates": [
            "completed example is visually separate from the independent activity",
            "independent answers are unmarked",
            "every box, line, circle and blank area has a named child action",
            *gates,
        ],
    }


PAGES: dict[str, dict[str, Any]] = {
    "LT-LKG-V4-P008": page(
        "Find the Difference", "Find visual differences between two similar scenes.",
        "Look carefully. Circle the five differences in Picture B.",
        "I compare one part at a time and circle only what changed.",
        {"pair": "two toy boats", "difference": "one flag is missing", "show_circle": True},
        "Five differences circled in the second playground scene.",
        "paired-scene-difference", "circle-five-differences", "logic-find-difference",
        {"playground_a": "playground scene with slide, ball, kite, bench and tree",
         "playground_b": "same playground with exactly five clear changes"},
        {"difference_count": 5, "circle_on": "picture_b", "labels": ["Picture A", "Picture B"],
         "differences": ["missing kite tail", "different ball colour", "absent flower", "shorter slide ladder", "bird facing other way"]},
        "Guide the child to compare the scenes from left to right without naming a difference.",
        "the two scenes have exactly five differences", "key objects are not cropped"),
    "LT-LKG-V4-P009": page(
        "Spot the Same", "Identify an identical picture among similar choices.",
        "Look at the picture on the left. Circle the picture that is exactly the same.",
        "I check shape, colour and direction before I choose.",
        {"target": "striped sock", "options": ["same sock", "different stripe", "reversed sock"], "answer": 1},
        "One identical picture circled in each of six rows.",
        "six-identical-picture-rows", "circle-identical-picture", "logic-spot-same",
        {"fish_set": "one target fish and three similar fish choices", "kite_set": "one target kite and three similar kite choices",
         "cup_set": "one target cup and three similar cup choices", "car_set": "one target car and three similar car choices",
         "butterfly_set": "one target butterfly and three similar butterfly choices", "shoe_set": "one target shoe and three similar shoe choices"},
        {"rows": ["fish", "kite", "cup", "car", "butterfly", "shoe"], "choices_per_row": 3, "answer_positions": [2, 3, 1, 3, 2, 1]},
        "Ask the child to name one detail that proves the pictures are the same.",
        "six substantial rows are present", "answer positions vary"),
    "LT-LKG-V4-P010": page(
        "Odd One Out", "Classify pictures and identify the item that does not belong.",
        "Name the pictures. Circle the one that does not belong in each row.",
        "I find what three pictures have in common, then choose the different one.",
        {"items": ["apple", "banana", "orange", "bus"], "answer": "bus", "show_circle": True},
        "One odd picture circled in each of six rows.",
        "six-odd-one-out-rows", "circle-category-outsider", "logic-odd-one-out",
        {"fruit_row": "three fruits and one vehicle", "animal_row": "three animals and one fruit",
         "clothes_row": "three clothes and one cup", "transport_row": "three vehicles and one flower",
         "shape_row": "three flat shapes and one ball", "weather_row": "three weather symbols and one shoe"},
        {"rows": ["fruit", "animals", "clothes", "transport", "shapes", "weather"], "items_per_row": 4,
         "answer_positions": [4, 2, 3, 1, 4, 2]},
        "Let the child name the group first, then ask which picture breaks the rule.",
        "object names appear below every picture", "six rows use different category rules"),
    "LT-LKG-V4-P011": page(
        "Picture Match", "Match familiar objects that are meaningfully related.",
        "Name each picture. Draw a line between the pictures that belong together.",
        "I think about how the two objects are used together.",
        {"left": "toothbrush", "right": "toothpaste", "show_completed_line": True},
        "Six lines connecting related object pairs.",
        "two-column-related-picture-match", "match-related-objects", "logic-picture-match",
        {"shoe": "one shoe", "key": "one key", "pencil": "one pencil", "cup": "one cup", "soap": "one bar of soap", "bed": "one bed",
         "sock": "one sock", "lock": "one padlock", "sharpener": "one pencil sharpener", "jug": "one water jug", "towel": "one towel", "pillow": "one pillow"},
        {"left": ["shoe", "key", "pencil", "cup", "soap", "bed"], "right": ["towel", "pillow", "sock", "sharpener", "lock", "jug"],
         "correct_pairs": [["shoe", "sock"], ["key", "lock"], ["pencil", "sharpener"], ["cup", "jug"], ["soap", "towel"], ["bed", "pillow"]], "require_derangement": True},
        "Ask how one matched pair is used together after the child draws the line.",
        "six matching pairs are included", "connector anchors are large and visible", "object names are printed"),
    "LT-LKG-V4-P012": page(
        "Hidden Objects", "Find familiar objects hidden within a controlled scene.",
        "Find each object shown below. Circle it in the classroom picture.",
        "I scan one small part of the picture at a time.",
        {"mini_scene": "toy shelf", "target": "red ball", "show_circle": True},
        "Six named target objects circled in the classroom scene.",
        "hidden-object-scene-with-target-strip", "find-and-circle-targets", "logic-hidden-objects",
        {"classroom_scene": "clean classroom scene hiding exactly six familiar objects", "ball": "red ball target", "key": "small key target",
         "spoon": "silver spoon target", "sock": "striped sock target", "pencil": "yellow pencil target", "teddy": "brown teddy target"},
        {"targets": ["ball", "key", "spoon", "sock", "pencil", "teddy"], "target_names_visible": True, "circle_in_scene": True},
        "Name one target at a time and allow the child time to scan the whole scene.",
        "scene contains exactly one of each target", "targets remain recognisable but not immediately obvious"),
    "LT-LKG-V4-P013": page(
        "What Comes Next", "Complete repeating visual sequences.",
        "Look for the repeating part. Circle the picture that comes next.",
        "I say the pattern aloud and use it to predict the next picture.",
        {"sequence": ["red apple", "green apple", "red apple", "green apple"], "answer": "red apple", "show_circle": True},
        "One next-picture choice circled in each of five sequences.",
        "five-sequence-choice-rows", "choose-next-picture", "logic-what-comes-next",
        {"star_pattern": "AB star pattern with three choices", "fruit_pattern": "AAB fruit pattern with three choices",
         "shape_pattern": "ABC shape pattern with three choices", "vehicle_pattern": "AB vehicle pattern with three choices",
         "animal_pattern": "AAB animal pattern with three choices"},
        {"rows": ["stars", "fruit", "shapes", "vehicles", "animals"], "pattern_types": ["AB", "AAB", "ABC", "AB", "AAB"], "choices_per_row": 3},
        "Point to each picture in order and pause before the blank.",
        "five rows are present", "each row includes one answer space and three choices"),
    "LT-LKG-V4-P014": page(
        "Story Sequence", "Arrange four events in a logical order.",
        "Look at the four pictures. Write 1, 2, 3 and 4 to show the story order.",
        "I find what happens first, next, then and last.",
        {"story": ["seed", "sprout", "small plant"], "numbers": [1, 2, 3], "show_answers": True},
        "Numbers 1–4 written once beside the four shuffled handwashing pictures.",
        "four-card-story-sequence", "number-events-in-order", "logic-story-sequence",
        {"wet_hands": "child wetting hands", "apply_soap": "child applying soap", "scrub_hands": "child scrubbing hands", "dry_hands": "child drying clean hands"},
        {"display_order": ["dry_hands", "wet_hands", "scrub_hands", "apply_soap"], "correct_order": ["wet_hands", "apply_soap", "scrub_hands", "dry_hands"],
         "writing_boxes": 4, "box_size_mm": 14},
        "Ask which picture must happen first and why; do not supply the number.",
        "all four writing boxes are empty", "each event is visibly distinct"),
    "LT-LKG-V4-P015": page(
        "Pattern Logic", "Recognise repeating picture patterns and draw what comes next.",
        "Say each pattern. Draw the next picture in the empty box.",
        "I find the part that repeats and draw what should follow.",
        {"sequence": ["circle", "square", "circle", "square"], "answer": "circle", "show_answer": True},
        "One next item drawn in each of five pattern boxes.",
        "five-draw-next-pattern-rows", "draw-next-pattern-item", "logic-pattern-logic",
        {"fruit_pattern": "AB apple-banana pattern", "shape_pattern": "AAB circle-triangle-triangle pattern",
         "toy_pattern": "ABC ball-car-teddy pattern", "flower_pattern": "AB red-blue flower pattern", "animal_pattern": "AAB cat-dog-dog pattern"},
        {"rows": ["fruit", "shapes", "toys", "flowers", "animals"], "pattern_types": ["AB", "AAB", "ABC", "AB", "AAB"],
         "draw_boxes": 5, "draw_box_min_mm": 22},
        "Have the child point to the repeating unit before drawing.",
        "five purposeful drawing boxes are provided", "no next item is prefilled"),
    "LT-LKG-V4-P016": page(
        "Complete the Series", "Predict the next item in changing visual series.",
        "Look at how each series changes. Circle the picture that comes next.",
        "I notice what changes in size, number, direction or position.",
        {"series": ["small star", "medium star", "large star"], "answer": "extra-large star", "show_circle": True},
        "One correct picture circled in each of five series.",
        "five-changing-series-rows", "choose-series-completion", "logic-complete-series",
        {"size_series": "objects growing in size with three choices", "count_series": "groups increasing by one with three choices",
         "direction_series": "arrow turning clockwise with three choices", "position_series": "ball moving through three boxes with choices",
         "colour_series": "colour cycle with three choices"},
        {"rows": ["size", "count", "direction", "position", "colour"], "choices_per_row": 3, "response": "circle"},
        "Ask what changed from one picture to the next before the child chooses.",
        "five distinct change rules are used", "choice circles remain unmarked"),
    "LT-LKG-V4-P017": page(
        "Sort by Colour", "Classify objects by colour.",
        "Find each picture's colour. Write red picture numbers in RED and blue picture numbers in BLUE.",
        "I ignore the object type and sort only by its colour.",
        {"picture": "red button", "number": 1, "category": "RED", "show_number_in_box": True},
        "Four picture numbers written in RED and four in BLUE.",
        "numbered-items-to-colour-groups", "write-picture-numbers-by-colour", "logic-sort-colour",
        {"red_button": "red button", "blue_cube": "blue cube", "blue_ball": "blue ball", "red_car": "red toy car",
         "blue_button": "blue button", "red_cube": "red cube", "red_ball": "red ball", "blue_car": "blue toy car"},
        {"items": ["red_button", "blue_cube", "blue_ball", "red_car", "blue_button", "red_cube", "red_ball", "blue_car"],
         "categories": ["RED", "BLUE"], "number_writing_boxes_per_category": 4, "correct_groups": {"RED": [1, 4, 6, 7], "BLUE": [2, 3, 5, 8]}},
        "Point to one number, name the object's colour, then let the child write that number in the matching group.",
        "each category has four separate number boxes", "all eight pictures have visible numbers and names"),
    "LT-LKG-V4-P018": page(
        "Sort by Shape", "Classify objects by their visible shape.",
        "Look at the numbered pictures. Write each number in the correct shape box.",
        "I look at the outside shape, not the colour.",
        {"picture": "round clock", "number": 1, "category": "CIRCLE", "show_number_in_box": True},
        "Three picture numbers written in each of the CIRCLE, SQUARE and TRIANGLE groups.",
        "numbered-items-to-shape-groups", "write-picture-numbers-by-shape", "logic-sort-shape",
        {"clock": "round wall clock", "window": "square window", "flag": "triangular flag", "plate": "round plate", "tile": "square tile",
         "sandwich": "triangular sandwich", "coin": "round coin", "gift_box": "square gift box", "road_sign": "triangular road sign"},
        {"items": ["clock", "window", "flag", "plate", "tile", "sandwich", "coin", "gift_box", "road_sign"],
         "categories": ["CIRCLE", "SQUARE", "TRIANGLE"], "number_writing_boxes_per_category": 3,
         "correct_groups": {"CIRCLE": [1, 4, 7], "SQUARE": [2, 5, 8], "TRIANGLE": [3, 6, 9]}},
        "Ask the child to trace each object’s outside edge in the air before sorting.",
        "three number boxes appear in every category", "nine pictures have visible numbers and names"),
    "LT-LKG-V4-P019": page(
        "Sort by Size", "Arrange familiar objects from smallest to largest.",
        "Write 1, 2 and 3 to order each set from smallest to largest.",
        "I compare the same kind of object and start with the smallest.",
        {"objects": ["small ball", "medium ball", "large ball"], "numbers": [1, 2, 3], "show_answers": True},
        "Numbers 1–3 written under every object in five shuffled size sets.",
        "five-three-size-order-sets", "number-smallest-to-largest", "logic-sort-size",
        {"bears": "three matching teddy bears in small, medium and large sizes", "trees": "three matching trees in small, medium and large sizes",
         "cups": "three matching cups in small, medium and large sizes", "fish": "three matching fish in small, medium and large sizes",
         "cars": "three matching cars in small, medium and large sizes"},
        {"sets": ["bears", "trees", "cups", "fish", "cars"], "items_per_set": 3,
         "display_orders": [[2, 3, 1], [3, 1, 2], [1, 3, 2], [2, 1, 3], [3, 2, 1]], "writing_boxes_per_set": 3},
        "Ask the child to point to the smallest, then the largest, before writing numbers.",
        "five size sets fill the page", "writing boxes are at least 12 mm"),
    "LT-LKG-V4-P020": page(
        "Belongs Together", "Identify familiar objects from the same functional group.",
        "Name each picture. Draw a line to the picture that belongs with it.",
        "I think about where objects are used and what they do.",
        {"left": "cup", "right": "plate", "reason": "things used for eating", "show_completed_line": True},
        "Six lines connecting objects that belong together.",
        "two-column-category-pair-match", "match-belonging-objects", "logic-belongs-together",
        {"pencil": "pencil", "shoe": "shoe", "soap": "bar of soap", "bed": "bed", "car": "car", "spoon": "spoon",
         "sharpener": "pencil sharpener", "sock": "sock", "towel": "towel", "pillow": "pillow", "garage": "garage", "bowl": "bowl"},
        {"left": ["pencil", "shoe", "soap", "bed", "car", "spoon"], "right": ["towel", "garage", "sharpener", "bowl", "pillow", "sock"],
         "correct_pairs": [["pencil", "sharpener"], ["shoe", "sock"], ["soap", "towel"], ["bed", "pillow"], ["car", "garage"], ["spoon", "bowl"]], "require_derangement": True},
        "Invite the child to explain one pair after matching it.",
        "six pairs are included", "object names and anchors are visible"),
    "LT-LKG-V4-P021": page(
        "Big Problem Small Problem", "Distinguish small everyday problems from problems needing adult help.",
        "Look at each numbered situation. Write its number under SMALL or BIG.",
        "I decide whether I can solve it safely or need an adult’s help.",
        {"situation": "dropped pencil", "category": "SMALL", "reason": "pick it up safely", "show_number_in_box": True},
        "Three picture numbers written under SMALL and three under BIG.",
        "numbered-situations-two-groups", "classify-problem-size", "logic-problem-size",
        {"broken_crayon": "child with a broken crayon", "spilled_water": "small cup of water spilled on a table",
         "missing_toy": "child looking for a toy", "smoke": "smoke coming from a kitchen", "hurt_knee": "child with a badly hurt knee", "lost_outside": "child lost outside"},
        {"items": ["broken_crayon", "spilled_water", "missing_toy", "smoke", "hurt_knee", "lost_outside"],
         "categories": ["SMALL", "BIG — TELL AN ADULT"], "number_writing_boxes_per_category": 3,
         "correct_groups": {"SMALL": [1, 2, 3], "BIG — TELL AN ADULT": [4, 5, 6]}},
        "Discuss safety: a big problem means stop and tell a trusted adult.",
        "safety situations are calm and non-frightening", "six response boxes are available"),
    "LT-LKG-V4-P022": page(
        "Cause and Effect", "Match familiar actions with likely outcomes.",
        "Look at each action. Draw a line to what is most likely to happen next.",
        "I ask, ‘What would happen because of this?’",
        {"cause": "plant is watered", "effect": "plant grows", "show_completed_line": True},
        "Five lines connecting each cause to its effect.",
        "cause-effect-two-column-match", "match-action-outcome", "logic-cause-effect",
        {"drop_ice": "ice cube left in sunlight", "push_ball": "child gently pushing a ball", "rain_cloud": "dark cloud releasing rain",
         "turn_switch": "finger turning on a lamp switch", "open_umbrella": "child opening an umbrella in rain",
         "puddle": "melted water puddle", "rolling_ball": "ball rolling away", "wet_ground": "wet ground with raindrops",
         "lit_lamp": "lamp glowing", "dry_child": "child staying dry under umbrella"},
        {"left": ["drop_ice", "push_ball", "rain_cloud", "turn_switch", "open_umbrella"],
         "right": ["lit_lamp", "puddle", "dry_child", "wet_ground", "rolling_ball"],
         "correct_pairs": [["drop_ice", "puddle"], ["push_ball", "rolling_ball"], ["rain_cloud", "wet_ground"], ["turn_switch", "lit_lamp"], ["open_umbrella", "dry_child"]], "require_derangement": True},
        "Ask the child to say ‘because’ when explaining one match.",
        "five cause-effect pairs are included", "events are safe and visually explicit"),
    "LT-LKG-V4-P023": page(
        "Left and Right", "Identify left and right positions.",
        "Look at each pair. Circle LEFT or RIGHT to tell where the first named object is.",
        "I use my own hands to remember left and right.",
        {"scene": "child between apple and ball", "direction": "Circle the ball on the right", "show_circle": True},
        "One correct object circled in each of six position scenes.",
        "six-left-right-choice-scenes", "circle-left-or-right-object", "logic-left-right",
        {"scene_1": "child with apple on left and ball on right", "scene_2": "tree with bird on left and kite on right",
         "scene_3": "box with car on left and teddy on right", "scene_4": "bench with flower on left and dog on right",
         "scene_5": "table with cup on left and plate on right", "scene_6": "gate with bus on left and bicycle on right"},
        {"scenes": ["scene_1", "scene_2", "scene_3", "scene_4", "scene_5", "scene_6"],
         "directions": ["right", "left", "right", "left", "right", "left"], "response": "circle"},
        "Stand beside the child and use the same viewing direction when naming left and right.",
        "six scenes are present", "the instruction for each scene is deterministic text"),
    "LT-LKG-V4-P024": page(
        "Above and Below", "Recognise objects above and below a reference point.",
        "Look at each picture. Circle the correct position word.",
        "I compare the object with the other object in the picture.",
        {"scene": "kite above a tree", "choices": ["above", "below"], "answer": "above", "show_circle": True},
        "One position word circled in each of six scenes.",
        "six-above-below-scenes", "circle-position-word", "logic-above-below",
        {"bird_tree": "bird above a tree", "shoe_chair": "shoe below a chair", "sun_cloud": "sun above a cloud",
         "cat_table": "cat below a table", "ball_shelf": "ball above a shelf", "fish_boat": "fish below a boat"},
        {"scenes": ["bird_tree", "shoe_chair", "sun_cloud", "cat_table", "ball_shelf", "fish_boat"],
         "choices": ["above", "below"], "answers": ["above", "below", "above", "below", "above", "below"], "minimum_choice_circle_mm": 18},
        "Ask ‘Where is it compared with the other object?’ before the child circles a word.",
        "position words fit comfortably inside large response targets", "six scenes are present"),
    "LT-LKG-V4-P025": page(
        "Inside and Outside", "Identify objects inside and outside containers or boundaries.",
        "Look at each picture. Circle the correct position word.",
        "I check whether the object is within the boundary or beyond it.",
        {"scene": "ball inside a box", "choices": ["inside", "outside"], "answer": "inside", "show_circle": True},
        "One position word circled in each of six scenes.",
        "six-inside-outside-scenes", "circle-location-word", "logic-inside-outside",
        {"ball_box": "ball inside an open box", "dog_kennel": "dog outside a kennel", "fish_bowl": "fish inside a bowl",
         "bird_cage": "bird outside an open cage", "toy_basket": "toy inside a basket", "child_house": "child outside a playhouse"},
        {"scenes": ["ball_box", "dog_kennel", "fish_bowl", "bird_cage", "toy_basket", "child_house"],
         "choices": ["inside", "outside"], "answers": ["inside", "outside", "inside", "outside", "inside", "outside"], "minimum_choice_circle_mm": 22},
        "Trace the boundary with a finger before asking inside or outside.",
        "full words fit inside response targets", "six clear boundary scenes are present"),
    "LT-LKG-V4-P026": page(
        "Maze Challenge", "Plan and trace a route through a simple maze.",
        "Trace a path from the rabbit to the carrot. Do not cross a wall.",
        "I look ahead before I choose a path.",
        {"maze": "tiny two-turn path from bee to flower", "show_completed_path": True},
        "One continuous pencil path from START to FINISH.",
        "single-large-trace-maze", "trace-unsolved-maze", "logic-maze",
        {"rabbit": "friendly rabbit start icon", "carrot": "large carrot finish icon"},
        {"grid": [8, 10], "start": [0, 8], "finish": [7, 1], "path_width_mm": 12, "show_solution": False,
         "dead_ends": 5, "start_label": "START", "finish_label": "FINISH"},
        "Ask the child to trace the route first with a finger, then with a pencil.",
        "maze is not pre-traced", "start and finish are obvious", "paths are wide enough for LKG pencil control"),
    "LT-LKG-V4-P027": page(
        "Remember the Pictures", "Build visual memory by recalling previously seen items.",
        "Look at the six pictures. Cover them. Then circle the three pictures you remember.",
        "I name the pictures, cover them and remember what I saw.",
        {"study_items": ["apple", "ball", "cup"], "recall_choices": ["apple", "car", "cup"], "answer": ["apple", "cup"], "show_circles": True},
        "Three remembered pictures circled from six recall choices after the study strip is covered.",
        "study-cover-recall", "remember-and-circle", "logic-memory-pictures",
        {"apple": "red apple", "ball": "striped ball", "cup": "blue cup", "car": "red toy car", "teddy": "brown teddy", "kite": "colourful kite",
         "recall_apple": "matching red apple", "recall_bus": "yellow bus distractor", "recall_cup": "matching blue cup", "recall_dog": "dog distractor",
         "recall_teddy": "matching brown teddy", "recall_flower": "flower distractor"},
        {"study_items": ["apple", "ball", "cup", "car", "teddy", "kite"], "recall_choices": ["recall_bus", "recall_teddy", "recall_dog", "recall_apple", "recall_flower", "recall_cup"],
         "correct_recall": ["recall_teddy", "recall_apple", "recall_cup"], "cover_instruction": True, "response": "circle"},
        "Allow ten seconds to study, then cover the study strip with a sheet of paper.",
        "study and recall areas are visually separate", "memory answers are not highlighted"),
    "LT-LKG-V4-P028": page(
        "Picture Recall", "Recall specific details from a previously viewed scene.",
        "Look at the scene for ten seconds. Cover it. Circle the answer to each question.",
        "I remember colours, numbers and positions from the scene.",
        {"scene": "girl with red umbrella and one dog", "question": "What colour was the umbrella?", "choices": ["red", "blue"], "answer": "red", "show_circle": True},
        "One answer circled for each of five recall questions.",
        "scene-study-and-five-recall-questions", "observe-cover-recall", "logic-picture-recall",
        {"park_scene": "simple park scene with a red kite, two birds, blue ball, one dog, yellow bench and girl beside tree"},
        {"study_seconds": 10, "cover_instruction": True, "questions": [
            {"prompt": "What colour was the kite?", "choices": ["red", "green"], "answer": "red"},
            {"prompt": "How many birds were there?", "choices": [1, 2, 3], "answer": 2},
            {"prompt": "What was beside the tree?", "choices": ["girl", "bus"], "answer": "girl"},
            {"prompt": "What colour was the ball?", "choices": ["blue", "yellow"], "answer": "blue"},
            {"prompt": "Which animal was there?", "choices": ["dog", "cat"], "answer": "dog"}]},
        "Cover the scene before reading the five questions; uncover it only after the child answers.",
        "five questions test distinct visual details", "answer targets are at least 15 mm"),
    "LT-LKG-V4-P029": page(
        "Choose the Best Answer", "Evaluate visual choices and select a sensible solution.",
        "Look at each problem. Circle the picture that shows the best choice.",
        "I think about which choice is safe, kind and useful.",
        {"problem": "rain begins", "options": ["open umbrella", "wear sunglasses", "drop bag"], "answer": "open umbrella", "show_circle": True},
        "One best-answer picture circled in each of five situations.",
        "five-situation-best-choice", "circle-best-visual-solution", "logic-best-answer",
        {"spill_problem": "small water spill with three response options", "friend_problem": "sad friend with three response options",
         "crossing_problem": "road crossing with three response options", "cold_problem": "cold weather with three clothing options",
         "lost_item_problem": "lost classroom pencil with three response options"},
        {"situations": ["spill", "sad_friend", "road", "cold", "lost_pencil"], "choices_per_situation": 3,
         "answers": ["wipe spill", "comfort friend", "use zebra crossing with adult", "wear coat", "ask and look calmly"]},
        "Ask the child to explain why one choice is safer or kinder.",
        "five independent situations are included", "unsafe distractors are non-frightening"),
    "LT-LKG-V4-P030": page(
        "Finish the Picture", "Use symmetry and visual clues to complete partial pictures.",
        "Look at each half-picture. Draw the missing half.",
        "I follow the lines and shapes already shown.",
        {"picture": "half butterfly", "completed_outline": "whole butterfly", "show_answer": True},
        "The missing half drawn in each of five purposeful drawing spaces.",
        "five-half-picture-drawing-tasks", "draw-missing-half", "logic-finish-picture",
        {"apple_half": "left half of a simple apple outline", "fish_half": "left half of a simple fish outline",
         "flower_half": "left half of a simple flower outline", "house_half": "left half of a simple house outline", "balloon_half": "left half of a balloon outline"},
        {"tasks": ["apple", "fish", "flower", "house", "balloon"], "centre_guides": True, "drawing_area_min_mm": [45, 35]},
        "Point out where each line meets the centre guide; let the child complete it independently.",
        "five drawing tasks fill the page", "no completed half appears in an independent task"),
    "LT-LKG-V4-P031": page(
        "Visual Puzzle", "Assemble matching picture pieces mentally.",
        "Look at each picture piece. Draw a line to the piece that completes it.",
        "I match colour, outline and picture detail at the cut edge.",
        {"left": "top half of apple", "right": "bottom half of apple", "show_completed_line": True},
        "Five lines connecting the matching halves.",
        "picture-half-two-column-match", "match-picture-halves", "logic-visual-puzzle",
        {"cat_top": "top half of cat picture", "bus_left": "left half of bus picture", "ball_top": "top half of ball picture",
         "flower_left": "left half of flower picture", "fish_top": "top half of fish picture", "fish_bottom": "matching bottom half of fish",
         "flower_right": "matching right half of flower", "cat_bottom": "matching bottom half of cat", "ball_bottom": "matching bottom half of ball", "bus_right": "matching right half of bus"},
        {"left": ["cat_top", "bus_left", "ball_top", "flower_left", "fish_top"],
         "right": ["fish_bottom", "flower_right", "cat_bottom", "ball_bottom", "bus_right"],
         "correct_pairs": [["cat_top", "cat_bottom"], ["bus_left", "bus_right"], ["ball_top", "ball_bottom"], ["flower_left", "flower_right"], ["fish_top", "fish_bottom"]], "require_derangement": True},
        "Ask the child to compare the cut edges before drawing each line.",
        "five matching pairs are included", "no object is cropped by the page frame"),
    "LT-LKG-V4-P032": page(
        "Shadow Match", "Match familiar objects to their silhouettes.",
        "Name each object. Draw a line to its shadow.",
        "I compare the outside shape and direction.",
        {"object": "spoon", "shadow": "spoon silhouette", "show_completed_line": True},
        "Six lines connecting objects to their correct shadows.",
        "object-to-shadow-two-column-match", "match-object-shadow", "logic-shadow-match",
        {"umbrella": "colourful umbrella", "boot": "rain boot", "teapot": "teapot", "guitar": "small guitar", "duck": "duck", "bicycle": "bicycle",
         "shadow_duck": "duck silhouette", "shadow_bicycle": "bicycle silhouette", "shadow_boot": "boot silhouette",
         "shadow_umbrella": "umbrella silhouette", "shadow_guitar": "guitar silhouette", "shadow_teapot": "teapot silhouette"},
        {"left": ["umbrella", "boot", "teapot", "guitar", "duck", "bicycle"],
         "right": ["shadow_duck", "shadow_bicycle", "shadow_boot", "shadow_umbrella", "shadow_guitar", "shadow_teapot"],
         "correct_pairs": [["umbrella", "shadow_umbrella"], ["boot", "shadow_boot"], ["teapot", "shadow_teapot"], ["guitar", "shadow_guitar"], ["duck", "shadow_duck"], ["bicycle", "shadow_bicycle"]], "require_derangement": True},
        "Encourage the child to trace an object’s outline in the air before matching.",
        "six pairs are present", "names appear below colour objects"),
    "LT-LKG-V4-P033": page(
        "Complete the Puzzle", "Use shape and picture clues to select missing pieces.",
        "Look at each picture with a missing piece. Circle the piece that fits.",
        "I match both the shape of the gap and the picture lines.",
        {"picture": "house with roof-piece gap", "choices": ["matching roof", "wheel", "leaf"], "answer": "matching roof", "show_circle": True},
        "One correct missing piece circled in each of five puzzles.",
        "five-missing-piece-puzzles", "choose-fitting-puzzle-piece", "logic-complete-puzzle",
        {"train_puzzle": "train picture with one missing piece and three choices", "fish_puzzle": "fish picture with one missing piece and three choices",
         "flower_puzzle": "flower picture with one missing piece and three choices", "kite_puzzle": "kite picture with one missing piece and three choices",
         "teddy_puzzle": "teddy picture with one missing piece and three choices"},
        {"puzzles": ["train", "fish", "flower", "kite", "teddy"], "choices_per_puzzle": 3, "response": "circle"},
        "Ask the child to check the gap shape before looking at picture details.",
        "five puzzles are included", "no correct piece is pre-inserted"),
    "LT-LKG-V4-P034": page(
        "Picture Logic", "Choose the picture that logically completes a set.",
        "Look at each picture set. Circle the picture that completes the rule.",
        "I compare what changes across the pictures.",
        {"set": ["empty cup", "half-full cup", "full cup"], "answer": "overflowing cup", "show_circle": True},
        "One logical completion circled in each of five sets.",
        "five-picture-logic-sets", "choose-logical-completion", "logic-picture-logic",
        {"growth_set": "seed-to-plant logic set with three choices", "weather_set": "weather-clothing logic set with choices",
         "meal_set": "plate-spoon-food relationship set", "home_set": "animal-home relationship set", "tool_set": "object-tool relationship set"},
        {"sets": ["growth", "weather", "meal", "animal_home", "tool_use"], "choices_per_set": 3, "response": "circle"},
        "Ask what rule connects the shown pictures before presenting the choices.",
        "five different logic relationships are used", "each set has three large answer choices"),
    "LT-LKG-V4-P035": page(
        "Simple Coding", "Follow directional symbols to reach a goal.",
        "Draw one arrow in each box to make a path from START to the goal.",
        "I move one square for each arrow and check my direction.",
        {"grid": [3, 3], "start": [0, 0], "code": ["right", "down"], "goal": [1, 1], "show_path": True},
        "Three unsolved paths traced correctly from their starts to their goals.",
        "three-grid-coding-paths", "trace-arrow-code", "logic-simple-coding",
        {"mouse": "mouse start icon", "cheese": "cheese goal icon", "bee": "bee start icon", "flower": "flower goal icon",
         "car": "car start icon", "garage": "garage goal icon"},
        {"tasks": [
            {"grid": [4, 4], "start": [0, 3], "goal": [3, 1], "code": ["right", "right", "right", "up", "up"]},
            {"grid": [4, 4], "start": [3, 3], "goal": [1, 0], "code": ["up", "up", "up", "left", "left"]},
            {"grid": [5, 4], "start": [0, 0], "goal": [4, 2], "code": ["right", "right", "down", "right", "right", "down"]}],
         "paths_dotted_not_solid": True, "show_solution": False},
        "Point to each arrow and move one grid square at a time; do not trace the path for the child.",
        "independent paths are dotted and unsolved", "arrow directions match the configured goals"),
    "LT-LKG-V4-P036": page(
        "Thinking Challenge", "Apply observation, classification and sequencing skills.",
        "Complete each thinking challenge.",
        "I read the small instruction for each challenge and use the right thinking skill.",
        {"task": "circle the odd fruit among three fruits and a bus", "answer": "bus", "show_circle": True},
        "Five independent responses: circle, match, order, find and choose.",
        "five-mixed-logic-challenges", "mixed-guided-logic", "logic-thinking-challenge",
        {"odd_one_out": "four-item odd-one-out set", "same_picture": "target and three same-picture choices",
         "pattern": "visual pattern with three answer choices", "size_order": "three bears in shuffled sizes", "shadow": "object with three shadow choices"},
        {"tasks": [
            {"type": "circle_odd", "asset": "odd_one_out"}, {"type": "circle_same", "asset": "same_picture"},
            {"type": "complete_pattern", "asset": "pattern"}, {"type": "number_order", "asset": "size_order"},
            {"type": "circle_shadow", "asset": "shadow"}]},
        "Read one short task instruction at a time and allow independent thinking.",
        "five varied tasks fill the page", "no task is pre-solved"),
    "LT-LKG-V4-P037": page(
        "Mixed Logic Review", "Review core observation, matching, sorting and pattern skills.",
        "Complete each review activity.",
        "I choose the thinking skill that fits each activity.",
        {"task": "match a key to a lock", "show_completed_line": True},
        "Six independent responses across six review activities.",
        "six-section-logic-review", "mixed-logic-review", "logic-mixed-review",
        {"difference_task": "small two-picture one-difference task", "match_task": "two related object pairs",
         "sort_task": "six numbered red-blue objects", "sequence_task": "four event pictures to number",
         "position_task": "two position scenes with word choices", "pattern_task": "two next-pattern rows"},
        {"tasks": ["find_difference", "match_pairs", "sort_colour", "story_sequence", "position_words", "complete_patterns"],
         "response_modes": ["circle", "line", "write numbers", "write order", "circle word", "draw next"]},
        "Give help only with reading the short instructions, not with the answers.",
        "six activities are present", "each section has its own response mechanic"),
    "LT-LKG-V4-P038": page(
        "Brain Challenge", "Solve age-appropriate visual brain teasers.",
        "Think carefully. Solve each picture puzzle.",
        "I try a strategy, check my answer and change it if needed.",
        {"assessment_safe": True, "label": "Try these by yourself"},
        "Five independent visual-puzzle responses.",
        "five-brain-teaser-cards", "independent-brain-challenges", "logic-brain-challenge",
        {"animal_pattern": "upright dog-cat-dog-cat pattern with one blank and three clearly separated choices", "path_count": "three simple paths with one reaching the goal",
         "balance_logic": "two visual balance clues and one question", "grid_oddity": "small grid with one different picture",
         "sequence_logic": "changing sequence with three choices"},
        {"tasks": ["animal_pattern", "path_count", "balance_logic", "grid_oddity", "sequence_logic"], "model_answers_visible": False},
        "Observe which strategy the child tries; do not demonstrate an assessment answer.",
        "assessment-like tasks have no solved model", "five response areas are clearly defined"),
    "LT-LKG-V4-P039": page(
        "Thinking Assessment", "Demonstrate independent learning across core logic skills.",
        "Complete each task by yourself. Your teacher will observe.",
        "I work carefully and check each answer.",
        {"assessment_safe": True, "label": "Independent assessment — no completed example"},
        "Six independent answers covering observation, classification, matching, sequence, position and coding.",
        "six-section-thinking-assessment", "independent-mixed-assessment", "logic-thinking-assessment",
        {"observation_task": "one-difference picture pair", "classification_task": "four-item odd-one-out set",
         "matching_task": "three object-shadow matches", "sequence_task": "three events to number",
         "position_task": "two spatial word questions", "coding_task": "one small unsolved arrow grid"},
        {"tasks": ["observation", "classification", "matching", "sequence", "position", "coding"], "completed_example": False,
         "teacher_scoring": [0, 1], "maximum_score": 6},
        "Read directions only; record whether each task is completed independently.",
        "no model answer appears", "all six tasks remain unmarked", "teacher scoring is outside the child activity"),
    "LT-LKG-V4-P040": page(
        "My Thinking Journal", "Reflect on a problem solved and the strategy used.",
        "Choose one thinking skill. Draw a problem you solved. Tell how you solved it.",
        "I remember a challenge and explain the thinking that helped me.",
        {"skill": "matching", "mini_example": "key connected to lock", "not_a_child_answer": True},
        "One selected skill, one purposeful drawing and one short dictated explanation.",
        "choice-draw-dictate-journal", "reflect-on-thinking", "logic-thinking-journal",
        {"observe_icon": "magnifying glass for observing", "match_icon": "two fitting puzzle pieces", "sequence_icon": "three ordered picture cards"},
        {"skill_choices": ["I observed", "I matched", "I put in order"], "choice_response": "tick one",
         "drawing_frame_count": 1, "drawing_frame_purpose": "Draw the problem I solved", "dictation_lines": 2,
         "dictation_starter": "I solved it by…"},
        "Ask the child to describe the drawing; write their words only if support is needed.",
        "exactly one drawing frame is used", "the two lines have a dictated-response purpose"),
    "LT-LKG-V4-P041": page(
        "Logic Celebration", "Celebrate specific reasoning skills learned in the book.",
        "Colour one badge for each thinking skill you used.",
        "I recognise the thinking skills I practised.",
        {"badge": "Observation Star", "one_section_coloured": True},
        "Five skill badges coloured by the child.",
        "five-colouring-skill-badges", "colour-achievement-badges", "logic-celebration",
        {"observe_badge": "outline badge with magnifying-glass icon", "match_badge": "outline badge with matching-pair icon",
         "sort_badge": "outline badge with sorting icon", "sequence_badge": "outline badge with ordered-cards icon",
         "solve_badge": "outline badge with puzzle-piece icon"},
        {"badges": ["I can observe", "I can match", "I can sort", "I can put in order", "I can solve"],
         "colouring_only": True, "badges_precoloured": False},
        "Name each skill and invite the child to recall one page where it was used.",
        "five badges are purposeful and uncoloured", "no parent panel appears"),
    "LT-LKG-V4-P042": page(
        "Certificate", "Celebrate completion of Logical Thinking Adventures.",
        "Write the child’s name, date and teacher’s signature.",
        "This certificate records completion of the book.",
        {"not_required": True, "certificate": True},
        "Name, date and teacher signature entered in deterministic certificate fields.",
        "deterministic-certificate", "complete-certificate-fields", "logic-certificate",
        {"logic_badge": "premium logic explorer badge without words", "corner_shapes": "small crop-safe logic-shape decoration"},
        {"fields": ["Child’s name", "Date", "Teacher’s signature"], "field_lines": 3,
         "publisher_text_deterministic": True, "official_logo_deterministic": True, "official_star_deterministic": True},
        "Complete the certificate after the child finishes the book.",
        "certificate text is deterministic", "no generated logo or mascot"),
    "LT-LKG-V4-P043": page(
        "I Am a Logic Explorer", "Celebrate confidence and success in logical thinking.",
        "Colour the explorer badge. Tick the thinking skill you enjoyed most.",
        "I celebrate what I can do and choose a favourite thinking skill.",
        {"badge": "small sample badge with one coloured star", "show_answer": True},
        "One badge coloured and one favourite skill ticked.",
        "hero-badge-and-skill-choice", "colour-and-self-select", "logic-explorer",
        {"hero_child": "one confident LKG child holding a magnifying glass beside large puzzle pieces",
         "explorer_badge": "large black-outline Logic Explorer colouring badge with no words",
         "observe_icon": "magnifying glass icon", "match_icon": "matching-pair icon", "solve_icon": "puzzle-piece icon"},
        {"badge_colouring_area": True, "skill_choices": ["Observe", "Match", "Solve"], "choice_response": "tick one",
         "official_star_deterministic": True},
        "Invite the child to name one challenge they are proud of solving.",
        "badge is large enough to colour", "three skill choices are child-readable"),
}


def main() -> int:
    expected = {f"LT-LKG-V4-P{number:03d}" for number in range(8, 44)}
    if set(PAGES) != expected:
        raise RuntimeError(f"Scope mismatch: missing={sorted(expected-set(PAGES))}; extra={sorted(set(PAGES)-expected)}")
    document = {
        "version": "1.0.0",
        "status": "READY_FOR_ILLUSTRATION_PRODUCTION",
        "book": "Logical Thinking Adventures",
        "level": "LKG (4+)",
        "scope": "LT-LKG-V4-P008 through LT-LKG-V4-P043",
        "authoritative_sources": [
            "production-prompts/logical-thinking-adventures/lkg/v4/release-manifest.json",
            "production-prompts/logical-thinking-adventures/lkg/v4/pages",
            "agent/phase2-five-page-pilot curriculum-first and response-safe rules",
        ],
        "global_rules": {
            "one_primary_child_action": True,
            "visible_completed_example": True,
            "independent_answers_unmarked": True,
            "parent_panel": False,
            "home_connection": False,
            "generic_response_panel": False,
            "every_response_area_has_a_named_action": True,
            "isolated_object_names_visible": True,
            "illustration_contains_no_generated_text": True,
            "worksheet_mechanics_are_deterministic": True,
            "allow_fallback": False,
            "minimum_child_text_pt_at_a4": 18,
            "minimum_response_target_mm": 12,
            "minimum_tasks_on_full_activity_page": 5,
        },
        "pages": PAGES,
    }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(document, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {len(PAGES)} Logical Thinking pages to {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
